version: '3.8'

services:
  api-gateway:
    build: ./apps/api-gateway
    container_name: api-gateway
    volumes:
      - ./apps/api-gateway:/srv/app
    ports:
      - "4000:4000"
    depends_on:
      - microservice-test

  microservice-test:
    build: ./apps/microservice-test
    container_name: microservice-test
    volumes:
      - ./apps/microservice-test:/srv/app
    ports:
      - "4001:4001"

  frontend:
    build: ./apps/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway