version: '3.8'

services:
  api-gateway:
    build: ./apps/api-gateway
    volumes:
      - ./apps/api-gateway:/srv/app
    ports:
      - "4000:4000"
    depends_on:
      - microservice-test

  microservice-test:
    build: ./apps/microservice-test
    volumes:
      - ./apps/microservice-test:/srv/app
    ports:
      - "4001:4001"

  frontend:
    build: ./apps/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/srv/app
      - nextjs_node_modules_data:/srv/app/node_modules
    depends_on:
      - api-gateway

volumes:
  nextjs_node_modules_data: